// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2023.2.2 (win64) Build 4126759 Thu Feb  8 23:53:51 MST 2024
// Date        : Thu May 16 18:37:35 2024
// Host        : lab817_01 running 64-bit major release  (build 9200)
// Command     : write_verilog -force -mode synth_stub
//               c:/zedboard_adrv9002_project/src_HDL/IP_802_11p/edit_IP_802_11p_v1_0.gen/sources_1/bd/block_design_0/ip/block_design_0_constellation_tracker_0_0/block_design_0_constellation_tracker_0_0_stub.v
// Design      : block_design_0_constellation_tracker_0_0
// Purpose     : Stub declaration of top-level module interface
// Device      : xc7z020clg484-1
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* x_core_info = "constellation_tracker,Vivado 2023.2.2" *)
module block_design_0_constellation_tracker_0_0(RESET, CLOCK, FFT_IDATA_IN, FFT_QDATA_IN, 
  FFT_DATA_IN_VALID, FFT_DATA_IN_LAST, FFT_DATA_IN_FIRST_SYMBOL_MARKER, 
  CONSTELLATION_IDATA_OUT, CONSTELLATION_QDATA_OUT, CONSTELLATION_DATA_OUT_VALID, 
  CONSTELLATION_DATA_OUT_FIRST_SYMBOL_MARKER, CONSTELLATION_BPSK_AMPLITUDE_REFERENCE, 
  ATAN_CONSTELLATION_IN_STROBE, ATAN_CONSTELLATION_IN_I, ATAN_CONSTELLATION_IN_Q, 
  ATAN_CONSTELLATION_IN_CNTR, ATAN_CONSTELLATION_PHASE_OUT_STROBE, 
  ATAN_CONSTELLATION_PHASE_OUT, ATAN_CONSTELLATION_AMPLITUDE_OUT, 
  ATAN_CONSTELLATION_PHASE_OUT_CNTR, ROTATION_CONSTELLATION_DATA_IN_STROBE, 
  ROTATION_CONSTELLATION_IDATA_IN, ROTATION_CONSTELLATION_QDATA_IN, 
  ROTATION_CONSTELLATION_PHASE_IN, ROTATION_CONSTELLATION_CNTR_IN, 
  ROTATION_CONSTELLATION_DATA_OUT_STROBE, ROTATION_CONSTELLATION_IDATA_OUT, 
  ROTATION_CONSTELLATION_QDATA_OUT, ROTATION_CONSTELLATION_DATA_OUT_CNTR)
/* synthesis syn_black_box black_box_pad_pin="RESET,FFT_IDATA_IN[23:0],FFT_QDATA_IN[23:0],FFT_DATA_IN_VALID,FFT_DATA_IN_LAST,FFT_DATA_IN_FIRST_SYMBOL_MARKER,CONSTELLATION_IDATA_OUT[23:0],CONSTELLATION_QDATA_OUT[23:0],CONSTELLATION_DATA_OUT_VALID,CONSTELLATION_DATA_OUT_FIRST_SYMBOL_MARKER,CONSTELLATION_BPSK_AMPLITUDE_REFERENCE[23:0],ATAN_CONSTELLATION_IN_STROBE,ATAN_CONSTELLATION_IN_I[23:0],ATAN_CONSTELLATION_IN_Q[23:0],ATAN_CONSTELLATION_IN_CNTR[5:0],ATAN_CONSTELLATION_PHASE_OUT_STROBE,ATAN_CONSTELLATION_PHASE_OUT[23:0],ATAN_CONSTELLATION_AMPLITUDE_OUT[23:0],ATAN_CONSTELLATION_PHASE_OUT_CNTR[5:0],ROTATION_CONSTELLATION_DATA_IN_STROBE,ROTATION_CONSTELLATION_IDATA_IN[23:0],ROTATION_CONSTELLATION_QDATA_IN[23:0],ROTATION_CONSTELLATION_PHASE_IN[23:0],ROTATION_CONSTELLATION_CNTR_IN[5:0],ROTATION_CONSTELLATION_DATA_OUT_STROBE,ROTATION_CONSTELLATION_IDATA_OUT[23:0],ROTATION_CONSTELLATION_QDATA_OUT[23:0],ROTATION_CONSTELLATION_DATA_OUT_CNTR[5:0]" */
/* synthesis syn_force_seq_prim="CLOCK" */;
  input RESET;
  input CLOCK /* synthesis syn_isclock = 1 */;
  input [23:0]FFT_IDATA_IN;
  input [23:0]FFT_QDATA_IN;
  input FFT_DATA_IN_VALID;
  input FFT_DATA_IN_LAST;
  input FFT_DATA_IN_FIRST_SYMBOL_MARKER;
  output [23:0]CONSTELLATION_IDATA_OUT;
  output [23:0]CONSTELLATION_QDATA_OUT;
  output CONSTELLATION_DATA_OUT_VALID;
  output CONSTELLATION_DATA_OUT_FIRST_SYMBOL_MARKER;
  output [23:0]CONSTELLATION_BPSK_AMPLITUDE_REFERENCE;
  output ATAN_CONSTELLATION_IN_STROBE;
  output [23:0]ATAN_CONSTELLATION_IN_I;
  output [23:0]ATAN_CONSTELLATION_IN_Q;
  output [5:0]ATAN_CONSTELLATION_IN_CNTR;
  input ATAN_CONSTELLATION_PHASE_OUT_STROBE;
  input [23:0]ATAN_CONSTELLATION_PHASE_OUT;
  input [23:0]ATAN_CONSTELLATION_AMPLITUDE_OUT;
  input [5:0]ATAN_CONSTELLATION_PHASE_OUT_CNTR;
  output ROTATION_CONSTELLATION_DATA_IN_STROBE;
  output [23:0]ROTATION_CONSTELLATION_IDATA_IN;
  output [23:0]ROTATION_CONSTELLATION_QDATA_IN;
  output [23:0]ROTATION_CONSTELLATION_PHASE_IN;
  output [5:0]ROTATION_CONSTELLATION_CNTR_IN;
  input ROTATION_CONSTELLATION_DATA_OUT_STROBE;
  input [23:0]ROTATION_CONSTELLATION_IDATA_OUT;
  input [23:0]ROTATION_CONSTELLATION_QDATA_OUT;
  input [5:0]ROTATION_CONSTELLATION_DATA_OUT_CNTR;
endmodule
