
///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////

package system_axi_hdmi_dma_0_pkg;

///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification
// environment.
///////////////////////////////////////////////////////////////////////////
  parameter system_axi_hdmi_dma_0_ID                      = 0;
  parameter system_axi_hdmi_dma_0_DMA_DATA_WIDTH_SRC      = 64;
  parameter system_axi_hdmi_dma_0_DMA_DATA_WIDTH_DEST     = 64;
  parameter system_axi_hdmi_dma_0_DMA_LENGTH_WIDTH        = 24;
  parameter system_axi_hdmi_dma_0_DMA_2D_TRANSFER         = 1;
  parameter system_axi_hdmi_dma_0_ASYNC_CLK_REQ_SRC       = 0;
  parameter system_axi_hdmi_dma_0_ASYNC_CLK_SRC_DEST      = 0;
  parameter system_axi_hdmi_dma_0_ASYNC_CLK_DEST_REQ      = 0;
  parameter system_axi_hdmi_dma_0_AXI_SLICE_DEST          = 0;
  parameter system_axi_hdmi_dma_0_AXI_SLICE_SRC           = 0;
  parameter system_axi_hdmi_dma_0_SYNC_TRANSFER_START     = 0;
  parameter system_axi_hdmi_dma_0_CYCLIC                  = 1;
  parameter system_axi_hdmi_dma_0_DMA_AXI_PROTOCOL_DEST   = 1;
  parameter system_axi_hdmi_dma_0_DMA_AXI_PROTOCOL_SRC    = 1;
  parameter system_axi_hdmi_dma_0_DMA_TYPE_DEST           = 1;
  parameter system_axi_hdmi_dma_0_DMA_TYPE_SRC            = 0;
  parameter system_axi_hdmi_dma_0_DMA_AXI_ADDR_WIDTH      = 29;
  parameter system_axi_hdmi_dma_0_MAX_BYTES_PER_BURST     = 128;
  parameter system_axi_hdmi_dma_0_FIFO_SIZE               = 8;
  parameter system_axi_hdmi_dma_0_AXI_ID_WIDTH_SRC        = 1;
  parameter system_axi_hdmi_dma_0_AXI_ID_WIDTH_DEST       = 1;
  parameter system_axi_hdmi_dma_0_DISABLE_DEBUG_REGISTERS = 0;
//////////////////////////////////////////////////////////////////////////

endpackage : system_axi_hdmi_dma_0_pkg
