/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver API: v0.0.0*/
/* Device Driver Client: v68.10.1*/
/* Firmware: v0.22.27*/
/* Profile Generator: v0.53.2.0*/
/* Stream Generator Assembly: v0.7.10.0*/
/* Transceiver Evaluation Software: v0.25.0*/
/* ADRV9001 Plugin: v0.25.0*/

#include "dataCapture.h"

int dataCapture(adi_fpga9001_Device_t * fpga9001Device_0)
{
	int32_t error_code = 0;

	adi_fpga9001_DmaCfg_t dmaCfg_0 = { 
		.length = 16384, 
		.continuous = false, 
		.timeout_ms = 300000, 
		.trigger = ADI_FPGA9001_DMA_TRIGGER_IMMEDIATE, 
		.captureType = ADI_FPGA9001_CAPTURE_TYPE_RX_DATA, 
		.dmaEnableSync = false };
	error_code = adi_fpga9001_DataChain_PerformTransfer(fpga9001Device_0, ADI_RX, ADI_CHANNEL_1, &dmaCfg_0);

	error_code = adi_fpga9001_DataChain_Data_Get_16I16QSigned(fpga9001Device_0, ADI_RX, ADI_CHANNEL_1, dataCapture_iData_1, dataCapture_qData_1, 4096);

	printf("adi_fpga9001_DataChain_Data_Get_16I16QSigned parameter 'iData' read back as '");
	printf("{ %ld", dataCapture_iData_1[0]);
	int32_t dataCapture_iData_1_indexer = 1;
	for (dataCapture_iData_1_indexer = 1; dataCapture_iData_1_indexer < 4096; dataCapture_iData_1_indexer++)
	{
		printf(", %ld", dataCapture_iData_1[dataCapture_iData_1_indexer]);
	}
	printf(" }\n");

	printf("adi_fpga9001_DataChain_Data_Get_16I16QSigned parameter 'qData' read back as '");
	printf("{ %ld", dataCapture_qData_1[0]);
	int32_t dataCapture_qData_1_indexer = 1;
	for (dataCapture_qData_1_indexer = 1; dataCapture_qData_1_indexer < 4096; dataCapture_qData_1_indexer++)
	{
		printf(", %ld", dataCapture_qData_1[dataCapture_qData_1_indexer]);
	}
	printf(" }\n");


	return error_code;
}
